<?php
/**
 * @file
 * Drupal module implementing New Relic
 */

/**
 * Implementation of hook_menu().
 */
function new_relic_rpm_menu() {
  $items['admin/content/new-relic-rpm'] = array(
    'title' => 'New Relic RPM deployment',
    'description' => "Create a new deployment for this site's App.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('new_relic_rpm_deploy'),
    'access arguments' => array('create new relic rpm deployments'),
    'file' => 'new_relic_rpm.settings.inc',
  );
  $items['admin/settings/new-relic-rpm'] = array(
    'title' => 'New Relic RPM Settings',
    'description' => 'Alter settings and mange your New Relic RPM Integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('new_relic_rpm_settings'),
    'access arguments' => array('administer new relic rpm'),
    'file' => 'new_relic_rpm.settings.inc',
  );
  $items['admin/reports/new-relic-rpm'] = array(
    'title' => 'New Relic RPM reports',
    'description' => 'View RPM reports and statistics.',
    'page callback' => 'new_relic_rpm_reporting',
    'access arguments' => array('view new relic rpm reports'),
    'file' => 'new_relic_rpm.reports.inc',
  );
  $items['admin/reports/new-relic-rpm/details/%'] = array(
    'title' => 'Application Details',
    'description' => 'Get details for a specific application.',
    'page callback' => 'new_relic_rpm_reporting_details',
    'page arguments' => array(4, 5),
    'access arguments' => array('view new relic rpm reports'),
    'file' => 'new_relic_rpm.reports.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function new_relic_rpm_perm() {
  return array(
    'administer new relic rpm',
    'view new relic rpm reports',
    'create new relic rpm deployments',
  );
}

/**
 * Implementation of hook_cron().
 *
 * This is used to set cron tasks to be not tracked by RPM if so desired.
 */
function new_relic_rpm_cron() {
  $cron_tracking = variable_get('new_relic_rpm_track_cron', 'norm');
  new_relic_rpm_set_job_state($cron_tracking);
}

/**
 * Implementation of hook_boot().
 *
 * This is used to set various RPM settings by URL.
 */
function new_relic_rpm_boot() {

  $ignore_urls = variable_get('new_relic_rpm_ignore_urls', '');
  $bg_urls = variable_get('new_relic_rpm_bg_urls', '');
  $exclu_urls = variable_get('new_relic_rpm_exclusive_urls', '');

  // Handle cases where this getting called from command line and q isn't set.
  $path = isset($_GET['q']) ? $_GET['q'] : '';

  if (!empty($exclu_urls)) {
    if (!new_relic_rpm_page_match($path, $exclu_urls)) {
      return new_relic_rpm_set_job_state('ignore');
    }
  }

  if (!empty($ignore_urls)) {
    if (new_relic_rpm_page_match($path, $ignore_urls)) {
      return new_relic_rpm_set_job_state('ignore');
    }
  }

  if (!empty($bg_urls)) {
    if (new_relic_rpm_page_match($path, $bg_urls)) {
      return new_relic_rpm_set_job_state('bg');
    }
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Add a submit action to the system_module enable/disable form
 */
function new_relic_rpm_form_system_modules_alter(&$form, &$form_state) {

  if (variable_get('new_relic_rpm_module_deployment', FALSE) &&
      // If the API Key and/or App name is/are not set, there is no sense in
      // attempting to create deployments.
      ini_get('newrelic.appname') &&
      variable_get('new_relic_rpm_api_key', '')) {

    // We need our module check to run first--before the actuall install is done by Drupal.
    $form['#submit'][-1000] = 'new_relic_rpm_modules_enabled';
    ksort($form['#submit']);
    reset($form['#submit']);
  }
}

function new_relic_rpm_set_job_state($setting) {
  static $newrelic_module;

  if (!isset($newrelic_module)) {
    $newrelic_module = function_exists('newrelic_background_job');
  }

  // If newrelic module isn't loaded into php, error and return.
  if (!$newrelic_module) {
    // Only throw error if we've booted far enough to watchdog.
    // i.e. drush updatedb
    if (function_exists('module_implements')) {
      watchdog('New Relic RPM', 'New Relic RPM PHP module not enabled.', array(), WATCHDOG_ERROR);
    }
    return;
  }

  switch ($setting) {
    case 'bg':
      newrelic_background_job(TRUE);
      break;

    case 'ignore':
      newrelic_ignore_transaction(TRUE);
      break;

  }
}

/**
 * Submit callback for system module page.
 *
 * Because we need to determine which modules Drupal is going to install, we
 * are going to perform the same actions as the actual module install process,
 * minus the actual installation of the modules.
 */
function new_relic_rpm_modules_enabled($form, &$form_state) {
  include_once './includes/install.inc';
  $new_modules = array();
  $enable_modules = array();
  $disable_modules = array();

  // If we are coming from the confirm form...
  if (!isset($form_state['storage'])) {
    // Merge in disabled active modules since they should be enabled.
    // They don't appear because disabled checkboxes are not submitted
    // by browsers.
    $form_state['values']['status'] = array_merge($form_state['values']['status'], $form_state['values']['disabled_modules']);

    // Check values for dependency that we can't install.
    $dependencies = system_module_build_dependencies($form_state['values']['validation_modules'], $form_state['values']);

  }
  else {
    $dependencies = NULL;
  }

  // Return if there are dependencies and they were not yet confirmed.
  if ($dependencies && !isset($form_state['values']['confirm'])) {
    return;
  }

  // Dependencies are covered. Drupal is going to install modules. Find out which.
  foreach ($form_state['values']['status'] as $key => $choice) {
    if ($choice) {
      if (drupal_get_installed_schema_version($key) == SCHEMA_UNINSTALLED) {
        $new_modules[] = $key;
      }
      else {
        $enable_modules[] = $key;
      }
    }
    else {
      $disable_modules[] = $key;
    }
  }

  // Validate new modules.
  foreach ($new_modules as $key => $module) {
    if (!drupal_check_module($module)) {
      unset($new_modules[$key]);
    }
  }

  $old_module_list = module_list();

  $new_modules = array_diff(array_merge($enable_modules, $new_modules), $old_module_list);
  $disable_modules = array_intersect($disable_modules, $old_module_list);

  // Make the Deploy call to New Relic.
  if (!empty($new_modules) || !empty($disable_modules)) {
    new_relic_rpm_module_deploy($new_modules, $disable_modules);
  }
}

/**
 * Log module enable/disable actions as a deploy call to New Relic RPM.
 */
function new_relic_rpm_module_deploy($new_modules, $disable_modules) {
  $modules_installed = !empty($new_modules);
  $modules_removed = !empty($disable_modules);

  if ($modules_installed) {
    $m_inst = 'Modules Installed: ' . implode(', ', $new_modules ) . "\n";
  }
  else {
    $m_inst = '';
  }

  if ($modules_removed) {
    $m_remv = 'Modules Removed: ' . implode(', ', $disable_modules) . "\n";
  }
  else {
    $m_remv = '';
  }

  _new_relic_rpm_deploy('Drupal Module Install/Uninstall',
    'Drupal modules were installed: ' . ($modules_installed ? 'YES' : 'NO') . ' and uninstalled: ' . ($modules_removed ? 'YES' : 'NO'),
    $m_inst . $m_remv);
}

/**
 * Send deployments to New Relic's web API.
 */
function _new_relic_rpm_deploy($user, $description, $changelog, $revision = NULL) {
  $post_vars['deployment[application_id]'] = ini_get('newrelic.appname');
  $post_vars['deployment[user]'] = $user;
  $post_vars['deployment[description]'] = $description;
  $post_vars['deployment[changelog]'] = $changelog;
  if (isset($revision)) {
    $post_vars['deployment[revision]'] = $revision;
  }
  $deployments = new_relic_rpm_curl('https://rpm.newrelic.com/deployments.xml', $post_vars);

  watchdog('New Relic RPM', 'Module install/uninstall action logged as deployment. Log data: %details', array('%details' => $deployments));
}

/**
 * This is the generic cURL function all New Relic Web API calls go through.
 */
function new_relic_rpm_curl($url, $post = array()) {

  $api_key = variable_get('new_relic_rpm_api_key', '');

  // Set the header with the API key.
  $headers[] = "http-x-license-key: {$api_key}";

  // Set up the cURL request.
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  if (!empty($post)) {
    curl_setopt($ch, CURLOPT_POST, TRUE);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
  }
  curl_setopt($ch, CURLOPT_TIMEOUT, 30);
  $return_data = curl_exec($ch);

  if (stristr($return_data, 'Access denied')) {
    return FALSE;
  }

  return $return_data;
}

/**
 * Check if a path matches any pattern in a set of patterns.
 *
 * This is a direct copy of drupal_match_path without the static cache since we
 * don't need it. This is needed because we need our hook_boot to be able to
 * operate before path.inc has been bootstrapped.
 *
 * @param $path
 *   The path to match.
 * @param $patterns
 *   String containing a set of patterns separated by \n, \r or \r\n.
 *
 * @return
 *   1 if there is a match, 0 if there is not a match.
 */
function new_relic_rpm_page_match($path, $patterns) {
  $regexp = '/^('. preg_replace(array('/(\r\n?|\n)/', '/\\\\\*/', '/(^|\|)\\\\<front\\\\>($|\|)/'), array('|', '.*', '\1'. preg_quote(variable_get('site_frontpage', 'node'), '/') .'\2'), preg_quote($patterns, '/')) .')$/';
  return preg_match($regexp, $path);
}
